### ISSUE TITLE
Translation files (.po) not in UTF-8

### ISSUE THREAD

**Issue by a-dekker** [Salamek/cron-descriptor#2]
I am having trouble displaying all languages in a proper way. The content of the PO files seems to be a variation of ASCII encodings in UTF-8 format. Encoding them in real UTF-8 would solve all those issues I think.

**Comment by Salamek** [comment]
@a-dekker it should be fixed now, can you pls check your language if its ok ? 
Thx

**Comment by a-dekker** [comment]
Looks fine looking at the files. Thanks for the update. Will report back as soon as I can test.

**Comment by a-dekker** [comment]
I can confirm the characters look okay now. Thanks again.

**Comment by Salamek** [comment]
happy to help :)
