### ISSUE TITLE
Inconsistent licensing ?

### ISSUE THREAD

**Issue by tcpip106** [Salamek/cron-descriptor#27]
The project is MIT license but some of the code has headers look like GPL: 
https://github.com/Salamek/cron-descriptor/blob/master/cron_descriptor/ExpressionParser.py

Would you please help clarify if the project is entirely MIT licensed, with GPL license headers included in error? 
Or is the project GPL licensed, with the contents of the LICENSE file being in error? 
Or is the project partly MIT-licensed and partly GPL-licensed, without the differently-licensed files being segregated?

Thanks for your help

**Comment by Salamek** [comment]
@tcpip106 sorry that was incorrectly configured IDE generating incorrect header in newly created files... This library is MIT licensed (If that is ok?).

**Comment by tcpip106** [comment]
Yes. Thanks for your help.
