### ISSUE TITLE
Incorrect description for (22 26 18 ? JAN,DEC WED#1,2 *)

### ISSUE THREAD

**Issue by ernestorefinepro** [Salamek/cron-descriptor#28]
Code:
```
from cron_descriptor import get_description, ExpressionDescriptor

print(get_description("22 26 18 ? JAN,DEC WED#1,1,2,3,4 *"))
```
Result: `At 06:26:22 PM, on the None Wednesday, Monday, Tuesday, Wednesday, and Thursday of the month, only in January and December`

Expected result: `At 06:26:22 PM, on the first Wednesday, Monday, Tuesday, Wednesday, and Thursday of the month, only in January and December`

**Comment by Salamek** [comment]
@ernestorefinepro I'm trying to stay 1:1 with https://github.com/bradymholt/cron-expression-descriptor in output format, so fixed to show this https://cronexpressiondescriptor.azurewebsites.net/?expression=22+26+18+%3F+JAN%2CDEC+WED%231%2C1%2C2%2C3%2C4+*&locale=en

Thx for report.
