### ISSUE TITLE
Weekdays not localized

### ISSUE THREAD

**Issue by a-dekker** [Salamek/cron-descriptor#4]
Hi Salamek,

I noticed the weekdays are not translated, while the rest of the string is. I made a small modification to get a localized day of week returned. I did not make a pull request as it is very small and perhaps you prefer a different solution.
Tools.py:

```
from .Exception import WrongArgumentException
from calendar import day_name


def number_to_day(day_number):
    """Returns day name by its number

    Args:
        day_number: Number of a day
    Returns:
        Day corresponding to day_number
    Raises:
        IndexError: When day_number is not found
    """
    return [day_name[6], day_name[0], day_name[1], day_name[2], day_name[3], day_name[4], day_name[5]][day_number]

```
number_to_month also return hard coded strings, but I do not see those returned in the results (always full month names).

**Comment by Salamek** [comment]
@a-dekker this  change will break cron parsing with differend language ten en_US, cos this function was also used to translate textual CRON month/day syntax (SUN-SAT, JAN-DEC) to its numeric representation in ExpressionParser.py:166-172

Commit c0790715e8b03c2ee682dbab7414ab1cdfa34bb6 fixes this ... all

**Comment by a-dekker** [comment]
I did not make that connection, so it is a good thing you made your own fix.
Going to test it right away, thanks.

**Comment by Salamek** [comment]
@a-dekker happy to help :-)
