### ISSUE TITLE
Schedule "*/10 */1 * * *" translated the same as schedule "*/10 * * * *"

### ISSUE THREAD

**Issue by wickmaster** [Salamek/cron-descriptor#56]
Using version `1.2.24` (latest) with Python `3.9.5`, I see the following:

```
>>> import cron_descriptor as cd
>>> cd.get_description("*/10 * * * *")
'Every 10 minutes'
>>> cd.get_description("*/10 */1 * * *")
'Every 10 minutes'
```

[Crontab guru](https://crontab.guru/) shows the following translations:
[`*/10 * * * *`](https://crontab.guru/#*/10_*_*_*_*) - "At every 10th minute."
[`*/10 */1 * * *`](https://crontab.guru/#*/10_*/1_*_*_*) - "At every 10th minute past every hour."

**Comment by Salamek** [comment]
Isn't that a same thing? 
"At every 10th minute." == "At every 10th minute past every hour."

**Comment by wickmaster** [comment]
Huh, well, I didn't think they were the same. The plain-English translations certainly seem to differ:
* "At every 10th minute." sounds to me like `12:00, 12:10, 12:20, 12:30, ...`
* "At every 10th minute past every hour." sounds to me like `12:10, 13:10, 14:10, 15:10, ...`
This is what I expected to see.

Checking the examples on 2 different web utilities ([Crontab guru](https://crontab.guru/), [Cron Helper](https://cron.help/)), though, both cases give matching results.

Apologies for the noise.
