### ISSUE TITLE
Missing translation string for spanish language

### ISSUE THREAD

**Issue by Borogum** [Salamek/cron-descriptor#62]
Hello,

msgid ", starting {0}" for spanish (es_ES) is not present. This causes missing parts on some descriptions.

Thank you

**Comment by Salamek** [comment]
PR's are welcomed... (i'm not fixing this my self since i don't know ES :( )

**Comment by Borogum** [comment]
PR created :)

**Comment by Salamek** [comment]
Released in 1.2.35
