### ISSUE TITLE
Incorrect range accepted

### ISSUE THREAD

**Issue by a-dekker** [Salamek/cron-descriptor#7]
Salamek,

De following string is accepted:
```
print(get_description("* * * * 6-3"))
Every minute, Saturday through Wednesday
```
That interpretation looks fine, but I was not able to find any cron flavour that would actually support a range starting with a higher start-value than end-value (although in this case this feature would have been a nice to have).

**Comment by Salamek** [comment]
@a-dekker well i'm not sure how to handle this... this library is meant to describe cron expression... (and that works)... it is not cron expression validator...  so i think this is NOTABUG and WONTFIX kind of issue ?

**Comment by a-dekker** [comment]
I think your remark makes sense in a way :-)

I'll close this issue then..
