### ISSUE TITLE
Automatically publish package sources and wheels using GitHub Actions CI/CD workflows

### ISSUE THREAD

**Issue by florianvazelle** [Salamek/cron-descriptor#78]
Hi :wave: 

I would like to know if it would be possible to push the package as a wheel in pypi ?

Accordingly to the [python packaging documentation](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/), there's a github worfklow that lets you build and publish automatically on pypi.

If you are interested I can submit a PR :slightly_smiling_face:

**Comment by Salamek** [comment]
Hi, i'm using gitlab runner for CI (see .gitlab-ci.yml) and using twine to publish packages... well i have implemented wheel upload there so i consider this as solved...
