### ISSUE TITLE
Add a __main__.py

### ISSUE THREAD

**Issue by eduardomezencio** [Salamek/cron-descriptor#79]
We could add a __main__.py to this project so that you would be able to run it in the terminal like:

```sh
> python -m cron_descriptor '* * * * *'
Every minute
```

**Comment by Salamek** [comment]
PRs welcomed...

**Comment by Salamek** [comment]
I guess so, looks like this check needs some fixes too

**Comment by eduardomezencio** [comment]
https://github.com/Salamek/cron-descriptor/pull/80
