### ISSUE TITLE
archlinux PKGBUILD

### ISSUE THREAD

**Issue by Tadly** [Salamek/cron-descriptor#8]
Hi there,

You got a PKGBUILD  in your project which is super nice.
Mind throwing that into the AUR?

If you don't feel like it, I could do that as well and maintain updates etc.

**Comment by Tadly** [comment]
Sorry...

kinda finished the scheduling bit of my backup app where I require your module so I went ahead and
added this package to the AUR myself.

https://aur.archlinux.org/packages/python-cron-descriptor/

If you want to take over ownership, let me know.

**Comment by Salamek** [comment]
@Tadly hi, i wanted to look at it ~tonight :-D
well i think it is ok as you did it, maybe just PR changed PKGBUILD

**Comment by Tadly** [comment]
@Salamek hehe, sorry again.
I changed quite a few things in the PKGBUILD (not sure if you've seen all the changes).
Anyway, I'll quickly PR it and than you can have a look at it and decide from there. :)

**Comment by Salamek** [comment]
#9 is closing this then
